<?php
/**
 * Enhanced CSV Export - ICT Assessment Portal
 * Supports filtering, date ranges, and includes media counts
 */

require_once 'config.php';
requireLogin();

// Get database connection
$db = Database::getInstance()->getConnection();

// Build query based on filters
$whereConditions = [];
$params = [];

// Date range filter
if (isset($_GET['date_from']) && !empty($_GET['date_from'])) {
    $whereConditions[] = "DATE(submission_date) >= ?";
    $params[] = $_GET['date_from'];
}

if (isset($_GET['date_to']) && !empty($_GET['date_to'])) {
    $whereConditions[] = "DATE(submission_date) <= ?";
    $params[] = $_GET['date_to'];
}

// Status filter
if (isset($_GET['status']) && !empty($_GET['status']) && $_GET['status'] !== 'all') {
    $whereConditions[] = "status = ?";
    $params[] = $_GET['status'];
}

// Facility type filter
if (isset($_GET['facility_type']) && !empty($_GET['facility_type']) && $_GET['facility_type'] !== 'all') {
    $whereConditions[] = "facility_type = ?";
    $params[] = $_GET['facility_type'];
}

// Location filter
if (isset($_GET['location']) && !empty($_GET['location']) && $_GET['location'] !== 'all') {
    $whereConditions[] = "location = ?";
    $params[] = $_GET['location'];
}

// Computer system filter
if (isset($_GET['computer_system']) && !empty($_GET['computer_system']) && $_GET['computer_system'] !== 'all') {
    $whereConditions[] = "computer_system = ?";
    $params[] = $_GET['computer_system'];
}

// Search filter
if (isset($_GET['search']) && !empty($_GET['search'])) {
    $searchTerm = '%' . $_GET['search'] . '%';
    $whereConditions[] = "(school_name LIKE ? OR contact_person LIKE ? OR contact_email LIKE ?)";
    $params[] = $searchTerm;
    $params[] = $searchTerm;
    $params[] = $searchTerm;
}

// Build WHERE clause
$whereClause = '';
if (!empty($whereConditions)) {
    $whereClause = ' WHERE ' . implode(' AND ', $whereConditions);
}

// Get submissions with filters
$sql = "SELECT s.*, 
        (SELECT COUNT(*) FROM media_uploads WHERE submission_id = s.id AND file_type = 'image') as image_count,
        (SELECT COUNT(*) FROM media_uploads WHERE submission_id = s.id AND file_type = 'video') as video_count
        FROM submissions s" . $whereClause . " ORDER BY submission_date DESC";

$stmt = $db->prepare($sql);
$stmt->execute($params);
$submissions = $stmt->fetchAll();

// Determine export type
$exportType = isset($_GET['type']) ? $_GET['type'] : 'full';
$includeMedia = (isAdmin() && $exportType === 'full');

// Generate filename
$filename = 'ict_assessment_';
if (!empty($_GET['date_from']) || !empty($_GET['date_to'])) {
    $filename .= isset($_GET['date_from']) ? $_GET['date_from'] : 'start';
    $filename .= '_to_';
    $filename .= isset($_GET['date_to']) ? $_GET['date_to'] : 'end';
} else {
    $filename .= date('Y-m-d');
}
$filename .= '_' . date('His') . '.csv';

// Set headers for CSV download
header('Content-Type: text/csv; charset=utf-8');
header('Content-Disposition: attachment; filename=' . $filename);
header('Cache-Control: max-age=0');
header('Pragma: public');

// Create output stream
$output = fopen('php://output', 'w');

// Add BOM for Excel UTF-8 compatibility
fprintf($output, chr(0xEF).chr(0xBB).chr(0xBF));

// Write metadata header
fputcsv($output, ['ICT Infrastructure Assessment - Export Report']);
fputcsv($output, ['Generated:', date('Y-m-d H:i:s')]);
fputcsv($output, ['Generated by:', $_SESSION['username']]);
fputcsv($output, ['Total Records:', count($submissions)]);

// Add filter information
if (!empty($whereConditions)) {
    fputcsv($output, ['']);
    fputcsv($output, ['Applied Filters:']);
    if (isset($_GET['date_from'])) fputcsv($output, ['Date From:', $_GET['date_from']]);
    if (isset($_GET['date_to'])) fputcsv($output, ['Date To:', $_GET['date_to']]);
    if (isset($_GET['status']) && $_GET['status'] !== 'all') fputcsv($output, ['Status:', $_GET['status']]);
    if (isset($_GET['facility_type']) && $_GET['facility_type'] !== 'all') fputcsv($output, ['Facility Type:', $_GET['facility_type']]);
    if (isset($_GET['location']) && $_GET['location'] !== 'all') fputcsv($output, ['Location:', $_GET['location']]);
    if (isset($_GET['search'])) fputcsv($output, ['Search Term:', $_GET['search']]);
}

// Empty row separator
fputcsv($output, ['']);
fputcsv($output, ['']);

// CSV Headers
$headers = [
    'ID',
    'School Name',
    'Contact Person',
    'Contact Phone',
    'Contact Email',
    'Dedicated Building',
    'Facility Type',
    'Status',
    'Health State',
    'Floor Area (Sqm)',
    'Meets Min Area (1000 Sqm)',
    'Total Size (Sqm)',
    'Number of Floors',
    'Location',
    'Computer System',
    'Number of Computers',
    'Meets Specifications',
    'Has Networking',
    'Internet Speed',
    'Number of Exits',
    'Conveniences',
    'Convenience Attached',
    'Is Furnished',
    'Furniture List',
    'Submission Date',
    'Submission Time',
    'IP Address'
];

// Add media columns for admin
if ($includeMedia) {
    $headers[] = 'Number of Images';
    $headers[] = 'Number of Videos';
    $headers[] = 'Total Media Files';
}

fputcsv($output, $headers);

// Add data rows
foreach ($submissions as $submission) {
    $submissionDateTime = new DateTime($submission['submission_date']);
    
    $row = [
        $submission['id'],
        $submission['school_name'],
        $submission['contact_person'],
        $submission['contact_phone'],
        $submission['contact_email'],
        $submission['dedicated_building'],
        $submission['facility_type'],
        $submission['status'],
        $submission['health_state'],
        $submission['floor_area'],
        $submission['meets_min_area'],
        $submission['total_size'] ?? '',
        $submission['num_floors'],
        $submission['location'],
        $submission['computer_system'],
        $submission['num_computers'],
        $submission['spec_meet'],
        $submission['has_networking'],
        $submission['internet_speed'],
        $submission['num_exits'],
        $submission['conveniences'],
        $submission['convenience_attached'],
        $submission['is_furnished'],
        $submission['furniture_list'],
        $submissionDateTime->format('Y-m-d'),
        $submissionDateTime->format('H:i:s'),
        $submission['ip_address']
    ];
    
    // Add media counts for admin
    if ($includeMedia) {
        $imageCount = $submission['image_count'] ?? 0;
        $videoCount = $submission['video_count'] ?? 0;
        $row[] = $imageCount;
        $row[] = $videoCount;
        $row[] = $imageCount + $videoCount;
    }
    
    fputcsv($output, $row);
}

// Add summary section at the end
fputcsv($output, ['']);
fputcsv($output, ['']);
fputcsv($output, ['SUMMARY STATISTICS']);
fputcsv($output, ['Total Submissions:', count($submissions)]);

// Calculate statistics
$completedCount = 0;
$uncompletedCount = 0;
$dedicatedBuildingYes = 0;
$meetsMinAreaYes = 0;
$totalComputers = 0;
$totalFloorArea = 0;

foreach ($submissions as $submission) {
    if ($submission['status'] === 'Completed') $completedCount++;
    if ($submission['status'] === 'Uncompleted') $uncompletedCount++;
    if ($submission['dedicated_building'] === 'Yes') $dedicatedBuildingYes++;
    if ($submission['meets_min_area'] === 'YES') $meetsMinAreaYes++;
    $totalComputers += $submission['num_computers'];
    $totalFloorArea += $submission['floor_area'];
}

fputcsv($output, ['Completed Facilities:', $completedCount]);
fputcsv($output, ['Uncompleted Facilities:', $uncompletedCount]);
fputcsv($output, ['Dedicated Buildings:', $dedicatedBuildingYes]);
fputcsv($output, ['Meets Minimum Area (1000 Sqm):', $meetsMinAreaYes]);
fputcsv($output, ['Total Computers:', number_format($totalComputers)]);
fputcsv($output, ['Total Floor Area:', number_format($totalFloorArea, 2) . ' Sqm']);
fputcsv($output, ['Average Floor Area:', count($submissions) > 0 ? number_format($totalFloorArea / count($submissions), 2) . ' Sqm' : '0']);
fputcsv($output, ['Average Computers per Facility:', count($submissions) > 0 ? number_format($totalComputers / count($submissions), 1) : '0']);

// Facility type breakdown
$facilityTypes = [];
foreach ($submissions as $submission) {
    $type = $submission['facility_type'];
    if (!isset($facilityTypes[$type])) {
        $facilityTypes[$type] = 0;
    }
    $facilityTypes[$type]++;
}

if (!empty($facilityTypes)) {
    fputcsv($output, ['']);
    fputcsv($output, ['FACILITY TYPE BREAKDOWN']);
    foreach ($facilityTypes as $type => $count) {
        fputcsv($output, [$type, $count]);
    }
}

// Computer system breakdown
$computerSystems = [];
foreach ($submissions as $submission) {
    $system = $submission['computer_system'];
    if (!isset($computerSystems[$system])) {
        $computerSystems[$system] = 0;
    }
    $computerSystems[$system]++;
}

if (!empty($computerSystems)) {
    fputcsv($output, ['']);
    fputcsv($output, ['COMPUTER SYSTEM BREAKDOWN']);
    foreach ($computerSystems as $system => $count) {
        fputcsv($output, [$system, $count]);
    }
}

// Location breakdown
$locations = [];
foreach ($submissions as $submission) {
    $location = $submission['location'];
    if (!isset($locations[$location])) {
        $locations[$location] = 0;
    }
    $locations[$location]++;
}

if (!empty($locations)) {
    fputcsv($output, ['']);
    fputcsv($output, ['LOCATION BREAKDOWN']);
    foreach ($locations as $location => $count) {
        fputcsv($output, [$location, $count]);
    }
}

fclose($output);

// Log the export activity
$filterDescription = '';
if (!empty($whereConditions)) {
    $filterParts = [];
    if (isset($_GET['date_from'])) $filterParts[] = 'from:' . $_GET['date_from'];
    if (isset($_GET['date_to'])) $filterParts[] = 'to:' . $_GET['date_to'];
    if (isset($_GET['status']) && $_GET['status'] !== 'all') $filterParts[] = 'status:' . $_GET['status'];
    if (isset($_GET['search'])) $filterParts[] = 'search:' . $_GET['search'];
    $filterDescription = ' with filters: ' . implode(', ', $filterParts);
}

logActivity(
    isAdmin() ? 'admin' : 'review',
    $_SESSION['username'],
    'EXPORT_CSV',
    'Exported ' . count($submissions) . ' submissions to CSV' . $filterDescription
);

exit();
?>